[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_BETA = "true"
  REACT_APP_GA_TRACKING_ID_BETA = "UA-86401488-14"
  REACT_APP_BUNGIE_CLIENT_ID = "35218"
  REACT_APP_BUNGIE_CLIENT_SECRET = "4YZeKd5WaQHVygeQJETsTJzaRbTOsQIgDxNo.YhDpmQ"
  REACT_APP_BUNGIE_API_KEY = "7ff64b6a285d4eafa081b84294cd68f8"

[[headers]]
  for = "/service-worker.js"

  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
